package rulebook

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const LockFileName = "axup.lock"

// Lock is the on-disk representation of resolved dep SHAs. Generated by
// `axup deps tidy`, consumed by every subsequent run for reproducibility.
type Lock struct {
	Deps []LockedDep `yaml:"deps"`
}

type LockedDep struct {
	Name    string `yaml:"name"`
	Git     string `yaml:"git"`
	Version string `yaml:"version"`
	Sha     string `yaml:"sha"`
}

func LoadLock(dir string) (*Lock, error) {
	path := filepath.Join(dir, LockFileName)
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", LockFileName, err)
	}
	var l Lock
	if err := yaml.Unmarshal(data, &l); err != nil {
		return nil, fmt.Errorf("parse %s: %w", LockFileName, err)
	}
	return &l, nil
}

func SaveLock(dir string, l *Lock) error {
	path := filepath.Join(dir, LockFileName)
	data, err := yaml.Marshal(l)
	if err != nil {
		return err
	}
	header := []byte("# axup.lock — managed by `axup deps tidy`. Do not edit by hand.\n")
	return os.WriteFile(path, append(header, data...), 0o644)
}

// Find returns the locked entry for a dep name, or nil if not present.
func (l *Lock) Find(name string) *LockedDep {
	if l == nil {
		return nil
	}
	for i := range l.Deps {
		if l.Deps[i].Name == name {
			return &l.Deps[i]
		}
	}
	return nil
}

// Reconcile compares the rulebook's declared deps against the lock and
// returns (a) the SHAs to use per dep, (b) whether the lock was missing/stale
// and the caller should write it back. It does NOT fail when the lock is
// missing — it resolves fresh and lets the caller persist the result. It DOES
// fail when the lock disagrees with the declared version (different git URL
// or different version string) — that signals an unintended divergence.
func Reconcile(deps []DepSpec, lock *Lock) (resolved map[string]string, changed bool, newLock *Lock, err error) {
	resolved = map[string]string{}
	newLock = &Lock{}
	for _, d := range deps {
		if d.Name == "" || d.Git == "" || d.Version == "" {
			return nil, false, nil, fmt.Errorf("dep entry must have name, git, version (got %+v)", d)
		}
		url := d.NormalizedURL()
		if entry := lock.Find(d.Name); entry != nil {
			if entry.Git != d.Git || entry.Version != d.Version {
				return nil, false, nil, fmt.Errorf("dep %q: rulebook declares (git=%s version=%s) but %s says (git=%s version=%s); run `axup deps tidy`",
					d.Name, d.Git, d.Version, LockFileName, entry.Git, entry.Version)
			}
			if !isSha(entry.Sha) || len(entry.Sha) < 7 {
				return nil, false, nil, fmt.Errorf("dep %q in %s has invalid sha %q", d.Name, LockFileName, entry.Sha)
			}
			resolved[d.Name] = strings.ToLower(entry.Sha)
			newLock.Deps = append(newLock.Deps, *entry)
			continue
		}
		// Not locked — resolve from version.
		sha, err := ResolveRef(url, d.Version)
		if err != nil {
			return nil, false, nil, err
		}
		resolved[d.Name] = sha
		newLock.Deps = append(newLock.Deps, LockedDep{
			Name: d.Name, Git: d.Git, Version: d.Version, Sha: sha,
		})
		changed = true
	}
	return resolved, changed, newLock, nil
}

// RefreshAll resolves every dep from scratch (ignoring any existing lock) and
// returns a brand-new lock. Used by `axup deps tidy`.
func RefreshAll(deps []DepSpec) (*Lock, error) {
	out := &Lock{}
	for _, d := range deps {
		if d.Name == "" || d.Git == "" || d.Version == "" {
			return nil, fmt.Errorf("dep entry must have name, git, version (got %+v)", d)
		}
		sha, err := ResolveRef(d.NormalizedURL(), d.Version)
		if err != nil {
			return nil, err
		}
		out.Deps = append(out.Deps, LockedDep{
			Name: d.Name, Git: d.Git, Version: d.Version, Sha: sha,
		})
	}
	return out, nil
}
